# .travis.yml
sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.4.2
    - IMAGE_NAME=restaurant-service
    - REPO_NAME=tascigorkem/restaurant-service
    - HEROKU_API_KEY=0ef60806-3929-42d7-a444-ad12f1ae0b9a

before_install:
  - docker build -f Dockerfile -t ${IMAGE_NAME} .
  - docker run -p 8080:8080 ${IMAGE_NAME}

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: cb-restaurant-service
  on:
    repo: $REPO_NAME
    branch: master