# .travis.yml
sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker


env:
  global:
    - DOCKER_COMPOSE_VERSION=1.4.2
    - IMAGE_NAME=restaurant-service
    - REPO_NAME=restaurant-service
    - HEROKU_API_KEY=0ef60806-3929-42d7-a444-ad12f1ae0b9a
#    - DOCKER_USER=tascigorkem
#    - DOCKER_PASS=

before_install:
# reinstall docker-compose at specific version
#  - sudo rm -f /usr/local/bin/docker-compose
#  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin


before_script:

script:
  - ./mvnw clean install -B -DskipTests

#after_success:
#  - docker login -u $DOCKER_USER -p $DOCKER_PASS
#  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH&amp;amp;amp;amp;amp;amp;amp;lt;span data-mce-type="bookmark" style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" class="mce_SELRES_start"&amp;amp;amp;amp;amp;amp;amp;gt;&amp;amp;amp;amp;amp;amp;amp;lt;/span&amp;amp;amp;amp;amp;amp;amp;gt;; fi`
#  - export IMAGE_NAME=sivaprasadreddy/jblogger
#  - docker build -t $IMAGE_NAME:$COMMIT .
#  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
#  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: cb-restaurant-service
  on:
    tags: true
    repo: "$REPO_NAME"
    branch: master