# .travis.yml
sudo: required
language: java
jdk:
  - openjdk11

env:
  global:
    - REPO_NAME=tascigorkem/restaurant-service
    - HEROKU_API_KEY=0ef60806-3929-42d7-a444-ad12f1ae0b9a

script:
  - ./mvnw clean install -B -DskipITs
#  - ./mvnw clean install -B -DskipTests

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: cb-restaurant-service
  on:
    repo: $REPO_NAME
    branch: master