# .travis.yml
#language: java
#jdk:
#  - openjdk11
services:
  - docker


env:
  global:
    - DOCKER_COMPOSE_VERSION=1.4.2
    - IMAGE_NAME=restaurant-service
    - HEROKU_API_KEY=0ef60806-3929-42d7-a444-ad12f1ae0b9a
#    - DOCKER_USER=tascigorkem
#    - DOCKER_PASS=

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin


before_script:
  - docker-compose up -d --build

#script:
#  - docker-compose exec users python manage.py test
#  - docker-compose exec users black project
#  - docker-compose exec users flake8 project

after_script:
  - docker-compose down

#deploy:
#  provider: heroku
#  api-key:
#    secure: "$HEROKU_API_KEY"
#  app: cb-restaurant-service
#  on:
#    tags: true
#    repo: "$IMAGE_NAME"